Sequence to Sequence Problem Type
h2oai/h2o-llmstudio pull request #308
Opened 2023-07-24 12:45 UTC by psinger

Todo:

- [ ] README
- [ ] Check merging / pipeline
- [ ] Default settings for dtype etc?
- [ ] Model card

2023-07-27 09:46 UTC, maxjeblick reviewed
Thanks a lot for adding this problem type, it looks in a very good state!

I would move `prepare_lora` and `generate` to separate functions to avoid code duplication (also, they will probably be needed for other potential problem types as well).
Apart from that, the code looks fine, will test it more the next days.

2023-07-28 10:12 UTC, psinger commented
Thx for the comments @maxjeblick - tried to address them.

2023-07-31 07:52 UTC, maxjeblick commented on llm_studio/src/utils/config_utils.py
> +    elif cfg_dict["problem_type"] == "text_sequence_to_sequence_modeling":
```
def load_config_yaml(path: str):
    """Loads config from yaml file

    Args:
        path: path of file to load from
    Returns:
        config object
    """
    with open(path, "r") as fp:
        cfg_dict = yaml.load(fp, Loader=yaml.FullLoader)

    problem_type = cfg_dict["problem_type"]
    module_name = f"llm_studio.python_configs.{problem_type}_config"
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError:
        raise NotImplementedError(f"Problem Type {problem_type} not implemented")
    return module.ConfigProblemBase.from_dict(cfg_dict)

```

This code snippet should work, may useful to switch to easy subsequent adding of new problem types.

2023-07-31 08:17 UTC, maxjeblick requested changes
Thanks for the changes! Some observations:

- Summary tab fails with `AttributeError: 'ConfigProblemBase' object has no attribute 'hf'`
- Train Data Insights currently shows decoded input ids, whereas the model uses prompt input ids. Maybe it is useful in general to show prompt input ids, instead of input ids? Could potentially also changed in #301.
- Mid-term, promoting `generate` and `prepare_lora` to dedicated functions (with corresponding arguments, `cfg`, `backbone`, ...) may be useful. We can leave it here as is and I can have a look in #317.

2023-08-02 07:36 UTC, maxjeblick commented on llm_studio/src/utils/config_utils.py
> +    elif cfg_dict["problem_type"] == "text_sequence_to_sequence_modeling":
You also leave as is, as it is already part of RLHF PR

2023-08-03 10:16 UTC, maxjeblick commented
The PR is probably good to merge after hf has been added to the config.

2023-08-03 11:27 UTC, psinger commented
Yes, I just noticed that I also need to adjust the summary model card now. On it.

2023-08-03 16:06 UTC, maxjeblick approved these changes
LGTM thanks!

One small issue:
`trust_remote_code` is not populated in the model card, should be easy to fix.

2023-08-04 13:26 UTC, merged