fix deepspeed w/ lora generate speed
h2oai/h2o-llmstudio pull request #513
Opened 2023-12-01 09:17 UTC by haqishen

2023-12-01 14:04 UTC, haqishen commented on llm_studio/src/models/text_causal_language_modeling_model.py
> +                    pass
https://github.com/huggingface/peft/blob/6a57472665b2b712a84e2bedd98945038283f7cc/src/peft/tuners/tuners_utils.py#L273-L287

modified from here.

2023-12-06 14:27 UTC, pascal-pfeiffer requested changes
Thanks a lot for the PR @haqishen 
Great improvement on the generate speed. On my tests, it was about 50% of the original time. (70B llama2 model)
Can you please fix the typing issues and comment on the changes that you made to the default settings? Otherwise lgtm, thanks again.

2023-12-06 14:29 UTC, pascal-pfeiffer commented
> 10x~20x faster than before.

Where did you see that huge speedup? I can confirm about twice the speed. So, 50% time for inference vs main branch.

2023-12-08 04:42 UTC, haqishen commented
@pascal-pfeiffer Thanks for the comments!

After fixing this issue, these three parameters will start to affect the generation speed. The larger they are set, the faster the speed will be. When I tested llama2 7B on 3xRTX6000, a setting of 1e9 allowed the generation speed to reach its peak, which is a tenfold increase compared to the original.

I am currently testing the maximum parameter settings for llama2 70B with 4xA6000. We then set the default parameters to this value. What do you think?

2023-12-08 06:46 UTC, pascal-pfeiffer commented
> @pascal-pfeiffer Thanks for the comments!
> 
> After fixing this issue, these three parameters will start to affect the generation speed. The larger they are set, the faster the speed will be. When I tested llama2 7B on 3xRTX6000, a setting of 1e9 allowed the generation speed to reach its peak, which is a tenfold increase compared to the main branch.
> 
> I am currently testing the maximum parameter settings for llama2 70B with 4xA6000. We then set the default parameters to this value. What do you think?

The RTX A6000 doesn't have NVLink, so any sharding will probably be bound by the inter GPU connection. I am not exactly sure how they translate to the shards. With 1e9, maybe it is just loading the full model to each card?

I'd really leave it at the original default (which worked for V100 cards) and expand the tooltip that this should be tuned as large as possible for the given memory. Unless there is a reliable automatic way to find optimum values.

2023-12-11 13:54 UTC, psinger commented
One thing I noticed to not work properly is a check for enough disk space before starting an experiment.

Getting `OSError: [Errno 28] No space left on device` while deepspeed saves weights.

2023-12-12 07:11 UTC, haqishen commented
> One thing I noticed to not work properly is a check for enough disk space before starting an experiment.
> 
> Getting `OSError: [Errno 28] No space left on device` while deepspeed saves weights.

In the previous PR, there was a commit (https://github.com/h2oai/h2o-llmstudio/pull/288/commits/62fc9c5052076c455b4fa3affe027c453bd0d8c5)  that saved the model directly in PyTorch format using Deepspeed. Later, due to suspicions that this code caused the model accuracy reduction issue mentioned by Judan, it was reverted. 

I will retest this code to try to resolve the issue you are encountering.

2023-12-14 04:15 UTC, haqishen commented on llm_studio/src/utils/modeling_utils.py
> -        model_size_in_bytes *= 2  # need double space for converting deepspeed engine.
by saving pytorch checkpoint directly for deepspeed, we don't need to `x2` for space check now.

2023-12-14 04:16 UTC, haqishen commented on llm_studio/src/utils/modeling_utils.py
> +        n_params = param.ds_numel if hasattr(param, "ds_numel") else param.numel()
fix bug for check disk space when using deepspeed

2023-12-14 04:16 UTC, haqishen commented on llm_studio/src/utils/modeling_utils.py
> +            status = model.save_16bit_model(path, "checkpoint.pth")
saving pytorch checkpoint directly for deepspeed

2023-12-14 04:32 UTC, haqishen commented
> The RTX A6000 doesn't have NVLink, so any sharding will probably be bound by the inter GPU connection. I am not exactly sure how they translate to the shards. With 1e9, maybe it is just loading the full model to each card?

Yeah, I think there's a high probability that this is the case. I have reverted the default values and made slight change to the corresponding doc. Please check: [f378fd8](https://github.com/h2oai/h2o-llmstudio/pull/513/commits/f378fd8dcb649668ea827da1742cbfda06842fdb)

2023-12-14 04:35 UTC, haqishen commented
> One thing I noticed to not work properly is a check for enough disk space before starting an experiment.
> 
> Getting `OSError: [Errno 28] No space left on device` while deepspeed saves weights.

Hi @psinger I've fixed the check disk space and save checkpoint issue you met and checked the metric of train-push-pull experiments, please try again! [c60ab87](https://github.com/h2oai/h2o-llmstudio/pull/513/commits/c60ab87b74cddd2ebe12e5cddafbeaab717a28ae)

2023-12-19 15:03 UTC, pascal-pfeiffer approved these changes
thanks for the fixes @haqishen 
lgtm !

2023-12-20 15:25 UTC, merged