Update transformers
h2oai/h2o-llmstudio pull request #539
Opened 2023-12-14 15:01 UTC by maxjeblick

This PR updates transformers version to 4.36.

By this, flash attention is supported (and enabled by default) natively, see https://twitter.com/efxmarty/status/1734931075367850385

2023-12-18 10:09 UTC, psinger requested changes
Overall, looks good, thx.

But let's discuss proper setting for config.

2023-12-18 10:24 UTC, maxjeblick commented on llm_studio/src/utils/modeling_utils.py
> +            # see https://github.com/fxmarty/transformers/
I did it manually, happy to split it differently. Not sure if there's a commonly used convention for this.

2023-12-18 13:00 UTC, psinger commented on llm_studio/src/utils/modeling_utils.py
> +            config._attn_implementation_internal = "flash_attention_2"
Got it, thx.
It seems one can pass it via the model constructor though:
https://huggingface.co/docs/transformers/perf_infer_gpu_one

2023-12-19 08:46 UTC, psinger approved these changes
@maxjeblick if you are confident this _internal setting is sufficient, let's merge
thx!!!

2023-12-19 14:48 UTC, merged