Apply chat template for HF
h2oai/h2o-llmstudio pull request #660
Opened 2024-04-08 02:24 UTC by haqishen

close #551

2024-04-22 15:37 UTC, pascal-pfeiffer requested changes
Thank you for working on that issue @haqishen .

A few things, I noticed:
- chat template is also applied to seq2seq models.
- chat template is not applied in the downloaded models.
- system prompt should be optional
- it probably doesn't need an extra cfg yaml for the unit tests, you can reuse the existing ones.

2024-05-07 07:47 UTC, haqishen commented
Hi @pascal-pfeiffer

Thanks for your comments and sorry for the late.

I have a few questions:

> chat template is not applied in the downloaded models.

Chat template actually is not used for building input text within the project (at least for now), so I don't get the point of this ↑ Do I miss something?

> system prompt should be optional

https://github.com/h2oai/h2o-llmstudio/pull/660/files#diff-002a8aeff9716c32e7b21b06df53b9905cae17ae5f75c398705384b1d9507295R107

It's controlled here, and also there is unit test for not using system prompt here:

https://github.com/h2oai/h2o-llmstudio/pull/660/files#diff-f62f85ce93eeb67e1138700aef5af102db092272242ac76b40d7ad6b9a69e71cR47

Or do I misunderstand your comment?

2024-05-07 11:10 UTC, pascal-pfeiffer commented
Thanks for asking, I'll try to clarify below:

> Chat template actually is not used for building input text within the project (at least for now), so I don't get the point of this ↑ Do I miss something?

The downloaded model should be identical to the one pushed to huggingface. There is little benefit of maintaining different versions especially in the critical chat template. So, my point is to align the build process for model zip vs huggingface model repo. 


> https://github.com/h2oai/h2o-llmstudio/pull/660/files#diff-002a8aeff9716c32e7b21b06df53b9905cae17ae5f75c398705384b1d9507295R107
> It's controlled here, and also there is unit test for not using system prompt here:
> https://github.com/h2oai/h2o-llmstudio/pull/660/files#diff-f62f85ce93eeb67e1138700aef5af102db092272242ac76b40d7ad6b9a69e71cR47
> Or do I misunderstand your comment?

1. Train a model with system prompt
2. Your PR will add a required system prompt to the chat template
3. User is not able to use the model without providing a system prompt, and face an error "TemplateError: Conversation roles must alternate system/user/assistant/user/assistant/..."

2024-05-08 03:56 UTC, haqishen commented
@pascal-pfeiffer

Thanks for your answer, it make a lot of sense.

The current logic is that if an LLM uses a system prompt during training, it must also use a system prompt during generation. Conversely, if the LLM does not use a system prompt during training, it cannot use one during generation.

Your idea is that whether or not an LLM uses a system prompt during training, there should be the option to choose whether to use a system prompt during generation. Is this understanding correct?

2024-05-08 08:48 UTC, pascal-pfeiffer commented
> The current logic is that if an LLM uses a system prompt during training, it must also use a system prompt during generation. Conversely, if the LLM does not use a system prompt during training, it cannot use one during generation

> Your idea is that whether or not an LLM uses a system prompt during training, there should be the option to choose whether to use a system prompt during generation. Is this understanding correct?

1. Train with system prompt -> Inference can be done **either with or without** system prompt. Glimpsing at the code below we even support `""` in system prompts, which removes the whole system part of the prompt. Which means this case can be covered in the training data.
```python
    def get_systems(self, cfg, df):
        if cfg.dataset.system_column != "None":
            if cfg.dataset.system_column not in df.columns:
                logger.warning(
                    f"System column {cfg.dataset.system_column} not found."
                    f"Disabling functionality."
                )
                systems = ["" for _ in range(len(self.prompts))]
            else:
                systems = df[cfg.dataset.system_column].astype(str).tolist()
        else:
            systems = ["" for _ in range(len(self.prompts))]
        return systems
```

2. Train without system prompt -> Inference can only be done **without** system prompt (already the case in your PR)

2024-05-09 08:03 UTC, haqishen commented
@pascal-pfeiffer 
Updated, please check!

2024-05-09 08:42 UTC, pascal-pfeiffer requested changes
Thanks for the changes @haqishen 
Only a few nitpicks in the code comments.

2024-05-09 08:42 UTC, pascal-pfeiffer commented on llm_studio/app_utils/hugging_face_utils.py
> +        tokenizer.chat_template = get_chat_template(cfg)
I don't see the template being used in classification tasks.

2024-05-09 08:42 UTC, pascal-pfeiffer commented on llm_studio/app_utils/sections/experiment.py
> +            tokenizer.chat_template = get_chat_template(cfg)
I don't see the template being used in classification tasks.

2024-05-09 08:42 UTC, pascal-pfeiffer commented on tests/src/utils/test_chat_template.py
> +    return expected.replace("\\n", "\n")
I honestly liked the old test better with explicit string.
This function itself looks like it needs a unit test.

2024-05-09 11:58 UTC, pascal-pfeiffer approved these changes
Thank you for quickly addressing the suggestions. Looks good to me!

2024-05-09 16:20 UTC, merged