Add new setting: prompt_column_separator
h2oai/h2o-llmstudio pull request #724
Opened 2024-05-24 12:09 UTC by pascal-pfeiffer

closes #483

2024-06-26 04:46 UTC, sherenem approved these changes

2024-06-26 04:46 UTC, sherenem commented
Docs LGTM, thank you!

2024-07-03 14:15 UTC, psinger requested changes
THX - overall looks good!

A little feedback:
- Shall we add a different default separator, like \n###\n or similar?
- I guess it is not possible to add a nesting that only triggers if multiple values are selected? Possible probably, but some work, not sure if worth.
- Otherwise I would suggest to add it to the tokenizer section though. It is a bit dominant on top.

2024-07-04 07:33 UTC, pascal-pfeiffer commented on llm_studio/python_configs/text_causal_language_modeling_config.py
> +    prompt_column_separator: str = ""
It was double space before, which is hard to see in the textbox and also a bit unusual. Decided to change it to double newlines now. Will push the changes in a bit. Wdyt?

2024-07-04 07:36 UTC, pascal-pfeiffer commented
> * Shall we add a different default separator, like \n###\n or similar?

After some thought, I decided to use `\n\n`, will push the changes in a bit.

> * I guess it is not possible to add a nesting that only triggers if multiple values are selected? Possible probably, but some work, not sure if worth.

I also thought about it, but couldn't find an easy way. It would also force us to use a trigger for the columns dropdown. 

> * Otherwise I would suggest to add it to the tokenizer section though. It is a bit dominant on top.

From a logical standpoint, I believe it should be a dataset setting.

2024-07-10 13:44 UTC, psinger approved these changes

2024-07-10 14:50 UTC, merged