Do not break app when experiment folder is missing
h2oai/h2o-llmstudio pull request #776
Opened 2024-07-19 13:48 UTC by psinger

Do not break the whole app as soon as an experiment folder is missing. 

Closes
https://github.com/h2oai/h2o-llmstudio/issues/757

2024-07-19 14:03 UTC, pascal-pfeiffer reviewed
Thank you! LGTM

Can/should we add this at least to the logger when the experiment was deleted? Ideally, The user would be notified and can remove these from the database.

2024-07-19 20:19 UTC, pascal-pfeiffer requested changes
I would really ask the user and delete the corresponding entries in the database. Current behavior is, that the experiment is still shown and the app subsequently crashes when I open the experiment and click on any of the other tabs, such as summary.

I mean, it is certainly better than having the app in a fully broken state, so we can also add in in another PR and I am happy to approve this as the first step.

2024-07-22 07:36 UTC, psinger commented
I find it personally this way better. Just keep it as-is. It is fine that the tabs fail, but then the whole app does not fail like it did now. It is a very edge case that this happens anyways.

2024-07-22 07:39 UTC, pascal-pfeiffer approved these changes

2024-07-22 07:53 UTC, merged